export const state = [
    {
      id: 1,
      groupType: "Group 1",
      machines: [
        {
          id: 1,
          machineAvailability: "Green",
          color: "#00FF00",
          generalInfo: [
            { id: 1, keyName: "Machine Model", value: "80%" },
            { id: 1, keyName: "Machine Make", value: "80%" },
            { id: 1, keyName: "Purchase Year", value: "80%" },
            { id: 1, keyName: "Ip Address", value: "80%" },
            { id: 1, keyName: "CNC Control Model", value: "80%" },
            { id: 1, keyName: "No of Axis", value: "80%" },
            { id: 1, keyName: "Company Name", value: "80%" },
          ],
          loadData: [
            { id: 1, keyName: "Current Load", value: "80%" },
            { id: 1, keyName: "Maximum Load", value: "80%" },
            { id: 1, keyName: "Minimum Load", value: "80%" },
            { id: 1, keyName: "Spindle Load", value: "80%" },
          ],
          productionData: [
            { id: 1, keyName: "Current Program Name", value: "80%" },
            { id: 1, keyName: "Projected Part Count", value: "80%" },
            { id: 1, keyName: "Actual Part Count", value: "80%" },
            { id: 1, keyName: "Cycle Time", value: "80%" },
            { id: 1, keyName: "Feet Rate", value: "80%" },
            { id: 1, keyName: "Spindle RPM", value: "80%" },
          ],
          alarmTrends: [
            { id: 1, keyName: "Emergency Stop", value: "80%" },
            { id: 1, keyName: "Hydrolic not on", value: "80%" },
            { id: 1, keyName: "Tool not clamp", value: "80%" },
          ],
          efficiency: [
            { id: 1, keyName: "Total Power on Time", value: "80%" },
            { id: 1, keyName: "Total Operaing time", value: "80%" },
            { id: 1, keyName: "Total Ideal Time", value: "80%" },
            { id: 1, keyName: "Total Efficiency", value: "80%" },
          ],
          offsetChange: [
            { id: 1, keyName: "Offset Change Max Value", value: "80%" },
            { id: 1, keyName: "Offset Change Min Value", value: "80%" },
            { id: 1, keyName: "Offset Change Current Value", value: "80%" },
          ],
        },
        { id: 2, machineAvailability: "Red", color: "#FF0000" , generalInfo: [
          { id: 1, keyName: "Machine Model", value: "80%" },
          { id: 1, keyName: "Machine Make", value: "80%" },
          { id: 1, keyName: "Purchase Year", value: "80%" },
          { id: 1, keyName: "Ip Address", value: "80%" },
          { id: 1, keyName: "CNC Control Model", value: "80%" },
          { id: 1, keyName: "No of Axis", value: "80%" },
          { id: 1, keyName: "Company Name", value: "80%" },
        ],
        loadData: [
          { id: 1, keyName: "Current Load", value: "80%" },
          { id: 1, keyName: "Maximum Load", value: "80%" },
          { id: 1, keyName: "Minimum Load", value: "80%" },
          { id: 1, keyName: "Spindle Load", value: "80%" },
        ],
        productionData: [
          { id: 1, keyName: "Current Program Name", value: "80%" },
          { id: 1, keyName: "Projected Part Count", value: "80%" },
          { id: 1, keyName: "Actual Part Count", value: "80%" },
          { id: 1, keyName: "Cycle Time", value: "80%" },
          { id: 1, keyName: "Feet Rate", value: "80%" },
          { id: 1, keyName: "Spindle RPM", value: "80%" },
        ],
        alarmTrends: [
          { id: 1, keyName: "Emergency Stop", value: "80%" },
          { id: 1, keyName: "Hydrolic not on", value: "80%" },
          { id: 1, keyName: "Tool not clamp", value: "80%" },
        ],
        efficiency: [
          { id: 1, keyName: "Total Power on Time", value: "80%" },
          { id: 1, keyName: "Total Operaing time", value: "80%" },
          { id: 1, keyName: "Total Ideal Time", value: "80%" },
          { id: 1, keyName: "Total Efficiency", value: "80%" },
        ],
        offsetChange: [
          { id: 1, keyName: "Offset Change Max Value", value: "80%" },
          { id: 1, keyName: "Offset Change Min Value", value: "80%" },
          { id: 1, keyName: "Offset Change Current Value", value: "80%" },
        ],},
        { id: 3, machineAvailability: "Grey", color: "grey" , generalInfo: [
          { id: 1, keyName: "Machine Model", value: "80%" },
          { id: 1, keyName: "Machine Make", value: "80%" },
          { id: 1, keyName: "Purchase Year", value: "80%" },
          { id: 1, keyName: "Ip Address", value: "80%" },
          { id: 1, keyName: "CNC Control Model", value: "80%" },
          { id: 1, keyName: "No of Axis", value: "80%" },
          { id: 1, keyName: "Company Name", value: "80%" },
        ],
        loadData: [
          { id: 1, keyName: "Current Load", value: "80%" },
          { id: 1, keyName: "Maximum Load", value: "80%" },
          { id: 1, keyName: "Minimum Load", value: "80%" },
          { id: 1, keyName: "Spindle Load", value: "80%" },
        ],
        productionData: [
          { id: 1, keyName: "Current Program Name", value: "80%" },
          { id: 1, keyName: "Projected Part Count", value: "80%" },
          { id: 1, keyName: "Actual Part Count", value: "80%" },
          { id: 1, keyName: "Cycle Time", value: "80%" },
          { id: 1, keyName: "Feet Rate", value: "80%" },
          { id: 1, keyName: "Spindle RPM", value: "80%" },
        ],
        alarmTrends: [
          { id: 1, keyName: "Emergency Stop", value: "80%" },
          { id: 1, keyName: "Hydrolic not on", value: "80%" },
          { id: 1, keyName: "Tool not clamp", value: "80%" },
        ],
        efficiency: [
          { id: 1, keyName: "Total Power on Time", value: "80%" },
          { id: 1, keyName: "Total Operaing time", value: "80%" },
          { id: 1, keyName: "Total Ideal Time", value: "80%" },
          { id: 1, keyName: "Total Efficiency", value: "80%" },
        ],
        offsetChange: [
          { id: 1, keyName: "Offset Change Max Value", value: "80%" },
          { id: 1, keyName: "Offset Change Min Value", value: "80%" },
          { id: 1, keyName: "Offset Change Current Value", value: "80%" },
        ],},
        { id: 4, machineAvailability: "Yellow", color: "#FFFF00" , generalInfo: [
          { id: 1, keyName: "Machine Model", value: "80%" },
          { id: 1, keyName: "Machine Make", value: "80%" },
          { id: 1, keyName: "Purchase Year", value: "80%" },
          { id: 1, keyName: "Ip Address", value: "80%" },
          { id: 1, keyName: "CNC Control Model", value: "80%" },
          { id: 1, keyName: "No of Axis", value: "80%" },
          { id: 1, keyName: "Company Name", value: "80%" },
        ],
        loadData: [
          { id: 1, keyName: "Current Load", value: "80%" },
          { id: 1, keyName: "Maximum Load", value: "80%" },
          { id: 1, keyName: "Minimum Load", value: "80%" },
          { id: 1, keyName: "Spindle Load", value: "80%" },
        ],
        productionData: [
          { id: 1, keyName: "Current Program Name", value: "80%" },
          { id: 1, keyName: "Projected Part Count", value: "80%" },
          { id: 1, keyName: "Actual Part Count", value: "80%" },
          { id: 1, keyName: "Cycle Time", value: "80%" },
          { id: 1, keyName: "Feet Rate", value: "80%" },
          { id: 1, keyName: "Spindle RPM", value: "80%" },
        ],
        alarmTrends: [
          { id: 1, keyName: "Emergency Stop", value: "80%" },
          { id: 1, keyName: "Hydrolic not on", value: "80%" },
          { id: 1, keyName: "Tool not clamp", value: "80%" },
        ],
        efficiency: [
          { id: 1, keyName: "Total Power on Time", value: "80%" },
          { id: 1, keyName: "Total Operaing time", value: "80%" },
          { id: 1, keyName: "Total Ideal Time", value: "80%" },
          { id: 1, keyName: "Total Efficiency", value: "80%" },
        ],
        offsetChange: [
          { id: 1, keyName: "Offset Change Max Value", value: "80%" },
          { id: 1, keyName: "Offset Change Min Value", value: "80%" },
          { id: 1, keyName: "Offset Change Current Value", value: "80%" },
        ],},
      ],
    },
    {
      id: 2,
      groupType: "Group 2",
      machines: [
        {
          id: 1,
          machineAvailability: "Green",
          color: "#00FF00",
          generalInfo: [
            { id: 1, keyName: "Machine Model", value: "80%" },
            { id: 1, keyName: "Machine Make", value: "80%" },
            { id: 1, keyName: "Purchase Year", value: "80%" },
            { id: 1, keyName: "Ip Address", value: "80%" },
            { id: 1, keyName: "CNC Control Model", value: "80%" },
            { id: 1, keyName: "No of Axis", value: "80%" },
            { id: 1, keyName: "Company Name", value: "80%" },
          ],
          loadData: [
            { id: 1, keyName: "Current Load", value: "80%" },
            { id: 1, keyName: "Maximum Load", value: "80%" },
            { id: 1, keyName: "Minimum Load", value: "80%" },
            { id: 1, keyName: "Spindle Load", value: "80%" },
          ],
          productionData: [
            { id: 1, keyName: "Current Program Name", value: "80%" },
            { id: 1, keyName: "Projected Part Count", value: "80%" },
            { id: 1, keyName: "Actual Part Count", value: "80%" },
            { id: 1, keyName: "Cycle Time", value: "80%" },
            { id: 1, keyName: "Feet Rate", value: "80%" },
            { id: 1, keyName: "Spindle RPM", value: "80%" },
          ],
          alarmTrends: [
            { id: 1, keyName: "Emergency Stop", value: "80%" },
            { id: 1, keyName: "Hydrolic not on", value: "80%" },
            { id: 1, keyName: "Tool not clamp", value: "80%" },
          ],
          efficiency: [
            { id: 1, keyName: "Total Power on Time", value: "80%" },
            { id: 1, keyName: "Total Operaing time", value: "80%" },
            { id: 1, keyName: "Total Ideal Time", value: "80%" },
            { id: 1, keyName: "Total Efficiency", value: "80%" },
          ],
          offsetChange: [
            { id: 1, keyName: "Offset Change Max Value", value: "80%" },
            { id: 1, keyName: "Offset Change Min Value", value: "80%" },
            { id: 1, keyName: "Offset Change Current Value", value: "80%" },
          ],
        },
        { id: 2, machineAvailability: "Red", color: "#FF0000" , generalInfo: [
          { id: 1, keyName: "Machine Model", value: "80%" },
          { id: 1, keyName: "Machine Make", value: "80%" },
          { id: 1, keyName: "Purchase Year", value: "80%" },
          { id: 1, keyName: "Ip Address", value: "80%" },
          { id: 1, keyName: "CNC Control Model", value: "80%" },
          { id: 1, keyName: "No of Axis", value: "80%" },
          { id: 1, keyName: "Company Name", value: "80%" },
        ],
        loadData: [
          { id: 1, keyName: "Current Load", value: "80%" },
          { id: 1, keyName: "Maximum Load", value: "80%" },
          { id: 1, keyName: "Minimum Load", value: "80%" },
          { id: 1, keyName: "Spindle Load", value: "80%" },
        ],
        productionData: [
          { id: 1, keyName: "Current Program Name", value: "80%" },
          { id: 1, keyName: "Projected Part Count", value: "80%" },
          { id: 1, keyName: "Actual Part Count", value: "80%" },
          { id: 1, keyName: "Cycle Time", value: "80%" },
          { id: 1, keyName: "Feet Rate", value: "80%" },
          { id: 1, keyName: "Spindle RPM", value: "80%" },
        ],
        alarmTrends: [
          { id: 1, keyName: "Emergency Stop", value: "80%" },
          { id: 1, keyName: "Hydrolic not on", value: "80%" },
          { id: 1, keyName: "Tool not clamp", value: "80%" },
        ],
        efficiency: [
          { id: 1, keyName: "Total Power on Time", value: "80%" },
          { id: 1, keyName: "Total Operaing time", value: "80%" },
          { id: 1, keyName: "Total Ideal Time", value: "80%" },
          { id: 1, keyName: "Total Efficiency", value: "80%" },
        ],
        offsetChange: [
          { id: 1, keyName: "Offset Change Max Value", value: "80%" },
          { id: 1, keyName: "Offset Change Min Value", value: "80%" },
          { id: 1, keyName: "Offset Change Current Value", value: "80%" },
        ],},
        { id: 3, machineAvailability: "Grey", color: "grey" , generalInfo: [
          { id: 1, keyName: "Machine Model", value: "80%" },
          { id: 1, keyName: "Machine Make", value: "80%" },
          { id: 1, keyName: "Purchase Year", value: "80%" },
          { id: 1, keyName: "Ip Address", value: "80%" },
          { id: 1, keyName: "CNC Control Model", value: "80%" },
          { id: 1, keyName: "No of Axis", value: "80%" },
          { id: 1, keyName: "Company Name", value: "80%" },
        ],
        loadData: [
          { id: 1, keyName: "Current Load", value: "80%" },
          { id: 1, keyName: "Maximum Load", value: "80%" },
          { id: 1, keyName: "Minimum Load", value: "80%" },
          { id: 1, keyName: "Spindle Load", value: "80%" },
        ],
        productionData: [
          { id: 1, keyName: "Current Program Name", value: "80%" },
          { id: 1, keyName: "Projected Part Count", value: "80%" },
          { id: 1, keyName: "Actual Part Count", value: "80%" },
          { id: 1, keyName: "Cycle Time", value: "80%" },
          { id: 1, keyName: "Feet Rate", value: "80%" },
          { id: 1, keyName: "Spindle RPM", value: "80%" },
        ],
        alarmTrends: [
          { id: 1, keyName: "Emergency Stop", value: "80%" },
          { id: 1, keyName: "Hydrolic not on", value: "80%" },
          { id: 1, keyName: "Tool not clamp", value: "80%" },
        ],
        efficiency: [
          { id: 1, keyName: "Total Power on Time", value: "80%" },
          { id: 1, keyName: "Total Operaing time", value: "80%" },
          { id: 1, keyName: "Total Ideal Time", value: "80%" },
          { id: 1, keyName: "Total Efficiency", value: "80%" },
        ],
        offsetChange: [
          { id: 1, keyName: "Offset Change Max Value", value: "80%" },
          { id: 1, keyName: "Offset Change Min Value", value: "80%" },
          { id: 1, keyName: "Offset Change Current Value", value: "80%" },
        ],},
        { id: 4, machineAvailability: "Yellow", color: "#FFFF00" , generalInfo: [
          { id: 1, keyName: "Machine Model", value: "80%" },
          { id: 1, keyName: "Machine Make", value: "80%" },
          { id: 1, keyName: "Purchase Year", value: "80%" },
          { id: 1, keyName: "Ip Address", value: "80%" },
          { id: 1, keyName: "CNC Control Model", value: "80%" },
          { id: 1, keyName: "No of Axis", value: "80%" },
          { id: 1, keyName: "Company Name", value: "80%" },
        ],
        loadData: [
          { id: 1, keyName: "Current Load", value: "80%" },
          { id: 1, keyName: "Maximum Load", value: "80%" },
          { id: 1, keyName: "Minimum Load", value: "80%" },
          { id: 1, keyName: "Spindle Load", value: "80%" },
        ],
        productionData: [
          { id: 1, keyName: "Current Program Name", value: "80%" },
          { id: 1, keyName: "Projected Part Count", value: "80%" },
          { id: 1, keyName: "Actual Part Count", value: "80%" },
          { id: 1, keyName: "Cycle Time", value: "80%" },
          { id: 1, keyName: "Feet Rate", value: "80%" },
          { id: 1, keyName: "Spindle RPM", value: "80%" },
        ],
        alarmTrends: [
          { id: 1, keyName: "Emergency Stop", value: "80%" },
          { id: 1, keyName: "Hydrolic not on", value: "80%" },
          { id: 1, keyName: "Tool not clamp", value: "80%" },
        ],
        efficiency: [
          { id: 1, keyName: "Total Power on Time", value: "80%" },
          { id: 1, keyName: "Total Operaing time", value: "80%" },
          { id: 1, keyName: "Total Ideal Time", value: "80%" },
          { id: 1, keyName: "Total Efficiency", value: "80%" },
        ],
        offsetChange: [
          { id: 1, keyName: "Offset Change Max Value", value: "80%" },
          { id: 1, keyName: "Offset Change Min Value", value: "80%" },
          { id: 1, keyName: "Offset Change Current Value", value: "80%" },
        ],},
      ],
    },
    {
      id: 3,
      groupType: "Group 3",
      machines: [
        {
          id: 1,
          machineAvailability: "Green",
          color: "#00FF00",
          generalInfo: [
            { id: 1, keyName: "Machine Model", value: "80%" },
            { id: 1, keyName: "Machine Make", value: "80%" },
            { id: 1, keyName: "Purchase Year", value: "80%" },
            { id: 1, keyName: "Ip Address", value: "80%" },
            { id: 1, keyName: "CNC Control Model", value: "80%" },
            { id: 1, keyName: "No of Axis", value: "80%" },
            { id: 1, keyName: "Company Name", value: "80%" },
          ],
          loadData: [
            { id: 1, keyName: "Current Load", value: "80%" },
            { id: 1, keyName: "Maximum Load", value: "80%" },
            { id: 1, keyName: "Minimum Load", value: "80%" },
            { id: 1, keyName: "Spindle Load", value: "80%" },
          ],
          productionData: [
            { id: 1, keyName: "Current Program Name", value: "80%" },
            { id: 1, keyName: "Projected Part Count", value: "80%" },
            { id: 1, keyName: "Actual Part Count", value: "80%" },
            { id: 1, keyName: "Cycle Time", value: "80%" },
            { id: 1, keyName: "Feet Rate", value: "80%" },
            { id: 1, keyName: "Spindle RPM", value: "80%" },
          ],
          alarmTrends: [
            { id: 1, keyName: "Emergency Stop", value: "80%" },
            { id: 1, keyName: "Hydrolic not on", value: "80%" },
            { id: 1, keyName: "Tool not clamp", value: "80%" },
          ],
          efficiency: [
            { id: 1, keyName: "Total Power on Time", value: "80%" },
            { id: 1, keyName: "Total Operaing time", value: "80%" },
            { id: 1, keyName: "Total Ideal Time", value: "80%" },
            { id: 1, keyName: "Total Efficiency", value: "80%" },
          ],
          offsetChange: [
            { id: 1, keyName: "Offset Change Max Value", value: "80%" },
            { id: 1, keyName: "Offset Change Min Value", value: "80%" },
            { id: 1, keyName: "Offset Change Current Value", value: "80%" },
          ],
        },
        { id: 2, machineAvailability: "Red", color: "#FF0000" , generalInfo: [
          { id: 1, keyName: "Machine Model", value: "80%" },
          { id: 1, keyName: "Machine Make", value: "80%" },
          { id: 1, keyName: "Purchase Year", value: "80%" },
          { id: 1, keyName: "Ip Address", value: "80%" },
          { id: 1, keyName: "CNC Control Model", value: "80%" },
          { id: 1, keyName: "No of Axis", value: "80%" },
          { id: 1, keyName: "Company Name", value: "80%" },
        ],
        loadData: [
          { id: 1, keyName: "Current Load", value: "80%" },
          { id: 1, keyName: "Maximum Load", value: "80%" },
          { id: 1, keyName: "Minimum Load", value: "80%" },
          { id: 1, keyName: "Spindle Load", value: "80%" },
        ],
        productionData: [
          { id: 1, keyName: "Current Program Name", value: "80%" },
          { id: 1, keyName: "Projected Part Count", value: "80%" },
          { id: 1, keyName: "Actual Part Count", value: "80%" },
          { id: 1, keyName: "Cycle Time", value: "80%" },
          { id: 1, keyName: "Feet Rate", value: "80%" },
          { id: 1, keyName: "Spindle RPM", value: "80%" },
        ],
        alarmTrends: [
          { id: 1, keyName: "Emergency Stop", value: "80%" },
          { id: 1, keyName: "Hydrolic not on", value: "80%" },
          { id: 1, keyName: "Tool not clamp", value: "80%" },
        ],
        efficiency: [
          { id: 1, keyName: "Total Power on Time", value: "80%" },
          { id: 1, keyName: "Total Operaing time", value: "80%" },
          { id: 1, keyName: "Total Ideal Time", value: "80%" },
          { id: 1, keyName: "Total Efficiency", value: "80%" },
        ],
        offsetChange: [
          { id: 1, keyName: "Offset Change Max Value", value: "80%" },
          { id: 1, keyName: "Offset Change Min Value", value: "80%" },
          { id: 1, keyName: "Offset Change Current Value", value: "80%" },
        ],},
        { id: 3, machineAvailability: "Grey", color: "grey" , generalInfo: [
          { id: 1, keyName: "Machine Model", value: "80%" },
          { id: 1, keyName: "Machine Make", value: "80%" },
          { id: 1, keyName: "Purchase Year", value: "80%" },
          { id: 1, keyName: "Ip Address", value: "80%" },
          { id: 1, keyName: "CNC Control Model", value: "80%" },
          { id: 1, keyName: "No of Axis", value: "80%" },
          { id: 1, keyName: "Company Name", value: "80%" },
        ],
        loadData: [
          { id: 1, keyName: "Current Load", value: "80%" },
          { id: 1, keyName: "Maximum Load", value: "80%" },
          { id: 1, keyName: "Minimum Load", value: "80%" },
          { id: 1, keyName: "Spindle Load", value: "80%" },
        ],
        productionData: [
          { id: 1, keyName: "Current Program Name", value: "80%" },
          { id: 1, keyName: "Projected Part Count", value: "80%" },
          { id: 1, keyName: "Actual Part Count", value: "80%" },
          { id: 1, keyName: "Cycle Time", value: "80%" },
          { id: 1, keyName: "Feet Rate", value: "80%" },
          { id: 1, keyName: "Spindle RPM", value: "80%" },
        ],
        alarmTrends: [
          { id: 1, keyName: "Emergency Stop", value: "80%" },
          { id: 1, keyName: "Hydrolic not on", value: "80%" },
          { id: 1, keyName: "Tool not clamp", value: "80%" },
        ],
        efficiency: [
          { id: 1, keyName: "Total Power on Time", value: "80%" },
          { id: 1, keyName: "Total Operaing time", value: "80%" },
          { id: 1, keyName: "Total Ideal Time", value: "80%" },
          { id: 1, keyName: "Total Efficiency", value: "80%" },
        ],
        offsetChange: [
          { id: 1, keyName: "Offset Change Max Value", value: "80%" },
          { id: 1, keyName: "Offset Change Min Value", value: "80%" },
          { id: 1, keyName: "Offset Change Current Value", value: "80%" },
        ],},
        { id: 4, machineAvailability: "Yellow", color: "#FFFF00" , generalInfo: [
          { id: 1, keyName: "Machine Model", value: "80%" },
          { id: 1, keyName: "Machine Make", value: "80%" },
          { id: 1, keyName: "Purchase Year", value: "80%" },
          { id: 1, keyName: "Ip Address", value: "80%" },
          { id: 1, keyName: "CNC Control Model", value: "80%" },
          { id: 1, keyName: "No of Axis", value: "80%" },
          { id: 1, keyName: "Company Name", value: "80%" },
        ],
        loadData: [
          { id: 1, keyName: "Current Load", value: "80%" },
          { id: 1, keyName: "Maximum Load", value: "80%" },
          { id: 1, keyName: "Minimum Load", value: "80%" },
          { id: 1, keyName: "Spindle Load", value: "80%" },
        ],
        productionData: [
          { id: 1, keyName: "Current Program Name", value: "80%" },
          { id: 1, keyName: "Projected Part Count", value: "80%" },
          { id: 1, keyName: "Actual Part Count", value: "80%" },
          { id: 1, keyName: "Cycle Time", value: "80%" },
          { id: 1, keyName: "Feet Rate", value: "80%" },
          { id: 1, keyName: "Spindle RPM", value: "80%" },
        ],
        alarmTrends: [
          { id: 1, keyName: "Emergency Stop", value: "80%" },
          { id: 1, keyName: "Hydrolic not on", value: "80%" },
          { id: 1, keyName: "Tool not clamp", value: "80%" },
        ],
        efficiency: [
          { id: 1, keyName: "Total Power on Time", value: "80%" },
          { id: 1, keyName: "Total Operaing time", value: "80%" },
          { id: 1, keyName: "Total Ideal Time", value: "80%" },
          { id: 1, keyName: "Total Efficiency", value: "80%" },
        ],
        offsetChange: [
          { id: 1, keyName: "Offset Change Max Value", value: "80%" },
          { id: 1, keyName: "Offset Change Min Value", value: "80%" },
          { id: 1, keyName: "Offset Change Current Value", value: "80%" },
        ],},
      ],
    },
    {
      id: 4,
      groupType: "Group 4",
      machines: [
        {
          id: 1,
          machineAvailability: "Green",
          color: "#00FF00",
          generalInfo: [
            { id: 1, keyName: "Machine Model", value: "80%" },
            { id: 1, keyName: "Machine Make", value: "80%" },
            { id: 1, keyName: "Purchase Year", value: "80%" },
            { id: 1, keyName: "Ip Address", value: "80%" },
            { id: 1, keyName: "CNC Control Model", value: "80%" },
            { id: 1, keyName: "No of Axis", value: "80%" },
            { id: 1, keyName: "Company Name", value: "80%" },
          ],
          loadData: [
            { id: 1, keyName: "Current Load", value: "80%" },
            { id: 1, keyName: "Maximum Load", value: "80%" },
            { id: 1, keyName: "Minimum Load", value: "80%" },
            { id: 1, keyName: "Spindle Load", value: "80%" },
          ],
          productionData: [
            { id: 1, keyName: "Current Program Name", value: "80%" },
            { id: 1, keyName: "Projected Part Count", value: "80%" },
            { id: 1, keyName: "Actual Part Count", value: "80%" },
            { id: 1, keyName: "Cycle Time", value: "80%" },
            { id: 1, keyName: "Feet Rate", value: "80%" },
            { id: 1, keyName: "Spindle RPM", value: "80%" },
          ],
          alarmTrends: [
            { id: 1, keyName: "Emergency Stop", value: "80%" },
            { id: 1, keyName: "Hydrolic not on", value: "80%" },
            { id: 1, keyName: "Tool not clamp", value: "80%" },
          ],
          efficiency: [
            { id: 1, keyName: "Total Power on Time", value: "80%" },
            { id: 1, keyName: "Total Operaing time", value: "80%" },
            { id: 1, keyName: "Total Ideal Time", value: "80%" },
            { id: 1, keyName: "Total Efficiency", value: "80%" },
          ],
          offsetChange: [
            { id: 1, keyName: "Offset Change Max Value", value: "80%" },
            { id: 1, keyName: "Offset Change Min Value", value: "80%" },
            { id: 1, keyName: "Offset Change Current Value", value: "80%" },
          ],
        },
        { id: 2, machineAvailability: "Red", color: "#FF0000" , generalInfo: [
          { id: 1, keyName: "Machine Model", value: "80%" },
          { id: 1, keyName: "Machine Make", value: "80%" },
          { id: 1, keyName: "Purchase Year", value: "80%" },
          { id: 1, keyName: "Ip Address", value: "80%" },
          { id: 1, keyName: "CNC Control Model", value: "80%" },
          { id: 1, keyName: "No of Axis", value: "80%" },
          { id: 1, keyName: "Company Name", value: "80%" },
        ],
        loadData: [
          { id: 1, keyName: "Current Load", value: "80%" },
          { id: 1, keyName: "Maximum Load", value: "80%" },
          { id: 1, keyName: "Minimum Load", value: "80%" },
          { id: 1, keyName: "Spindle Load", value: "80%" },
        ],
        productionData: [
          { id: 1, keyName: "Current Program Name", value: "80%" },
          { id: 1, keyName: "Projected Part Count", value: "80%" },
          { id: 1, keyName: "Actual Part Count", value: "80%" },
          { id: 1, keyName: "Cycle Time", value: "80%" },
          { id: 1, keyName: "Feet Rate", value: "80%" },
          { id: 1, keyName: "Spindle RPM", value: "80%" },
        ],
        alarmTrends: [
          { id: 1, keyName: "Emergency Stop", value: "80%" },
          { id: 1, keyName: "Hydrolic not on", value: "80%" },
          { id: 1, keyName: "Tool not clamp", value: "80%" },
        ],
        efficiency: [
          { id: 1, keyName: "Total Power on Time", value: "80%" },
          { id: 1, keyName: "Total Operaing time", value: "80%" },
          { id: 1, keyName: "Total Ideal Time", value: "80%" },
          { id: 1, keyName: "Total Efficiency", value: "80%" },
        ],
        offsetChange: [
          { id: 1, keyName: "Offset Change Max Value", value: "80%" },
          { id: 1, keyName: "Offset Change Min Value", value: "80%" },
          { id: 1, keyName: "Offset Change Current Value", value: "80%" },
        ],},
        { id: 3, machineAvailability: "Grey", color: "grey" , generalInfo: [
          { id: 1, keyName: "Machine Model", value: "80%" },
          { id: 1, keyName: "Machine Make", value: "80%" },
          { id: 1, keyName: "Purchase Year", value: "80%" },
          { id: 1, keyName: "Ip Address", value: "80%" },
          { id: 1, keyName: "CNC Control Model", value: "80%" },
          { id: 1, keyName: "No of Axis", value: "80%" },
          { id: 1, keyName: "Company Name", value: "80%" },
        ],
        loadData: [
          { id: 1, keyName: "Current Load", value: "80%" },
          { id: 1, keyName: "Maximum Load", value: "80%" },
          { id: 1, keyName: "Minimum Load", value: "80%" },
          { id: 1, keyName: "Spindle Load", value: "80%" },
        ],
        productionData: [
          { id: 1, keyName: "Current Program Name", value: "80%" },
          { id: 1, keyName: "Projected Part Count", value: "80%" },
          { id: 1, keyName: "Actual Part Count", value: "80%" },
          { id: 1, keyName: "Cycle Time", value: "80%" },
          { id: 1, keyName: "Feet Rate", value: "80%" },
          { id: 1, keyName: "Spindle RPM", value: "80%" },
        ],
        alarmTrends: [
          { id: 1, keyName: "Emergency Stop", value: "80%" },
          { id: 1, keyName: "Hydrolic not on", value: "80%" },
          { id: 1, keyName: "Tool not clamp", value: "80%" },
        ],
        efficiency: [
          { id: 1, keyName: "Total Power on Time", value: "80%" },
          { id: 1, keyName: "Total Operaing time", value: "80%" },
          { id: 1, keyName: "Total Ideal Time", value: "80%" },
          { id: 1, keyName: "Total Efficiency", value: "80%" },
        ],
        offsetChange: [
          { id: 1, keyName: "Offset Change Max Value", value: "80%" },
          { id: 1, keyName: "Offset Change Min Value", value: "80%" },
          { id: 1, keyName: "Offset Change Current Value", value: "80%" },
        ],},
        { id: 4, machineAvailability: "Yellow", color: "#FFFF00" , generalInfo: [
          { id: 1, keyName: "Machine Model", value: "80%" },
          { id: 1, keyName: "Machine Make", value: "80%" },
          { id: 1, keyName: "Purchase Year", value: "80%" },
          { id: 1, keyName: "Ip Address", value: "80%" },
          { id: 1, keyName: "CNC Control Model", value: "80%" },
          { id: 1, keyName: "No of Axis", value: "80%" },
          { id: 1, keyName: "Company Name", value: "80%" },
        ],
        loadData: [
          { id: 1, keyName: "Current Load", value: "80%" },
          { id: 1, keyName: "Maximum Load", value: "80%" },
          { id: 1, keyName: "Minimum Load", value: "80%" },
          { id: 1, keyName: "Spindle Load", value: "80%" },
        ],
        productionData: [
          { id: 1, keyName: "Current Program Name", value: "80%" },
          { id: 1, keyName: "Projected Part Count", value: "80%" },
          { id: 1, keyName: "Actual Part Count", value: "80%" },
          { id: 1, keyName: "Cycle Time", value: "80%" },
          { id: 1, keyName: "Feet Rate", value: "80%" },
          { id: 1, keyName: "Spindle RPM", value: "80%" },
        ],
        alarmTrends: [
          { id: 1, keyName: "Emergency Stop", value: "80%" },
          { id: 1, keyName: "Hydrolic not on", value: "80%" },
          { id: 1, keyName: "Tool not clamp", value: "80%" },
        ],
        efficiency: [
          { id: 1, keyName: "Total Power on Time", value: "80%" },
          { id: 1, keyName: "Total Operaing time", value: "80%" },
          { id: 1, keyName: "Total Ideal Time", value: "80%" },
          { id: 1, keyName: "Total Efficiency", value: "80%" },
        ],
        offsetChange: [
          { id: 1, keyName: "Offset Change Max Value", value: "80%" },
          { id: 1, keyName: "Offset Change Min Value", value: "80%" },
          { id: 1, keyName: "Offset Change Current Value", value: "80%" },
        ],},
      ],
    },
  ];
export const dataLink=state[0].machines[0]